### ISSUE TITLE
Update Amazon PostgreSQL RDS

### ISSUE THREAD

**Issue by cmhodgson** [InfraPM/regionalroads#153]
https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-aurora-rds-extended-support-mysql-postgresql-databases/

**Comment by cmhodgson** [comment]
If we do not move to a newer version of postgres, support for 11 is expiring and we will have to pay for amazon extended support which is about $0.10 - $0.12 /hour *24*30 = $72/month . We only have until feb 29 to complete this or start paying the charges. Refractions also has an RDS test/dev instance which needs to be upgraded as well, we can test the upgrade process there. Amazon has  blue-green migration option where you can create a new db instance on the new postgres version, with logical replication from the existing version - then test against it, and switch to it when ready. https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/blue-green-deployments.html

**Comment by al-tabb** [comment]
Thanks for flagging this Chris.  It sounds like a good approach to test the upgrade on the Refractions apps.  Do you know if there is extra cost for a blue-green deployment?

**Comment by cmhodgson** [comment]
I think the only cost is the for the extra resources of the second database instance (cpu and storage). These should only be required for a relatively short time, days or weeks, so shouldn't be too bad. I think for various reasons we probably want to schedule this to happen in a relatively short span of time. I don't expect any problems honestly, but we should be able to identify and resolve them on our dev server first anyway, so that we might only need hours to do the switchover. 

I suggest something like the following
- make sure our dev server has all the latest code and data from prod
- setup the blue-green replica on our dev postgres to the latest available postgres version
- point our dev server app at the replica and do a basic test of read-only operations (you can't write to the replica)
- switch over to the new version as the main one for our dev instance
- test more thoroughly all operations
- implement any necessary fixes and apply them to your staging env (if backwards compatible)
- test them and push them through to prod
- setup the blue-green replica on your prod db
- point the staging app at the new replica and test basic read only operations
- switch to the new version on prod (maybe on an evening for minimal impact)

I would suggest we upgrade to 16.1-R1 which is the latest postgresql engine version supported by AWS. Postgresql released v16 in september 2023 and v16.1 in november so I think any initial bugs should be worked out now.

**Comment by al-tabb** [comment]
Sure, this sounds like a good plan.  Can you provide an estimate?

**Comment by gleeming** [comment]
Estimate: 1 day ($1,320)
Emily is already running v14 locally, so we aren't anticipating any significant surprises.  We should know early on in the process if there are unexpected changes that might require additional effort.

**Comment by al-tabb** [comment]
Sounds good, please proceed. Thanks again for being proactive on issues like this.

**Comment by cmhodgson** [comment]
After a little more work and testing, we think the blue-green deployment option may be a bit more effort than is necessary. I just directly upgraded our RDS Postgresql instance from 11.19 to 11.22 and then to 16.1, it only takes about 15 minutes of downtime. 

The only change that we had to make was to enable SSL connection to postgres in the geoserver store config, because the new default configuration for postgres 14+ is to require SSL. Some of the stores on the production geoserver were configured to allow or prefer SSL, while some were set to DISABLE - I've set them all to at least "ALLOW" now. No other changes to the code or anything were required. 

I propose we perform the same upgrade on the prod server, perhaps Tuesday evening next week? Given that you have the RDS backups configured, we can setup a new db from the latest backup if anything went wrong in the upgrade, but I don't expect any problems. IIRC you have some kind of "maintenance mode" flag we can set that disables access to RegionalRoads?

Or do you think you need to provide a longer notice time to your users for 15-30 mins of downtime after business hours?

**Comment by al-tabb** [comment]
Tuesday evening next week sounds good.  Given how little the app is used outside of business hours and the short time frame of the outage I don't think any special notice is required.  I did set up a way to redirect users to /maintenance.php using a .htaccess file although I'm not sure it worked 100% of the time.  I believe the tricky part was trying to allow myself to still use the site and block others (recall that weird issue where it's difficult for me to get a solid answer on my own ip address).  If you'd like to use that approach I would suggest editing the .htaccess file to just redirect all traffic.  Then you just need to go into httpd.conf and change the regionalroads directory to allow overrides.

**Comment by al-tabb** [comment]
Please make a backup of the dev, staging and production databases just before doing the upgrade.  Thanks.
